[package]
name = "dev/dino-royale"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.1"
TableUtil = "sleitnick/table-util@1.2.0"

[server-dependencies]
# Server-only packages

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
